workspace(name = "algorithm_book")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
git_repository(
    name = "gtest",
    remote = "https://github.com/google/googletest",
    branch = "v1.10.x",
)

git_repository(
    name = "benchmark",
    remote = "https://github.com/google/benchmark",
    branch = "v1.5.1",
)